name: Nuget Package Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pack nuget Package
        run: dotnet pack --configuration Release
      - name: Push package to Nuget
        run: dotnet nuget push -s http://baget.simnopt.net:5000/v3/index.json -k ${{ secrets.NUGET_DEPLOY_KEY }} **/*.nupkg 
