name: Nuget Package Deploy

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
#    - name: Test with
#      run: dotnet test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Pack nuget Package
        run: dotnet pack --configuration Release
      - name: Push package to Nuget
        run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_DEPLOY_KEY }} -s http://ifvwnuget.simnopt.net/nuget
